### ISSUE TITLE
no docked results

### ISSUE THREAD

**Issue by Jooyun1983** [MolAICal/tutorials#1]
It is totally awesome and grateful to share these useful algorithms in MolAICal. I carried out the molecular generation (-denovo grow) using your example in the 000-quickStart, but these results, generated ligands are not docked to the target protein. I set up vina in the same folder and wrote target information such as centerPoints, boxLengthXYZ, and receptorPDB in the input file, InputParFile.dat. What's the problem?

**Comment by MolAICal** [comment]
> It is totally awesome and grateful to share these useful algorithms in MolAICal. I carried out the molecular generation (-denovo grow) using your example in the 000-quickStart, but these results, generated ligands are not docked to the target protein. I set up vina in the same folder and wrote target information such as centerPoints, boxLengthXYZ, and receptorPDB in the input file, InputParFile.dat. What's the problem?

Could you paste your problems here next time: [https://github.com/MolAICal/molaical.github.io/issues](https://github.com/MolAICal/molaical.github.io/issues). Then, I can reply problems together.

Docking requires certain steps. Please try this tutorial: [https://molaical.github.io/MolDocking.html](https://molaical.github.io/MolDocking.html)

Thanks,
Qifeng

**Comment by Jooyun1983** [comment]
Ok, I will try to do! Thanks~
