### ISSUE TITLE
How to get file namely stripDCD.vmd?

### ISSUE THREAD

**Issue by purnawanpp** [MolAICal/tutorials#2]
How to get the file, namely stripDCD.vmd? 
because I cannot find in VMD plugin.

**Comment by MolAICal** [comment]
> How to get the file, namely stripDCD.vmd? because I cannot find in VMD plugin.

Please download MolAICal [(https://molaical.github.io),](https://molaical.github.io) and decompress it. "stripDCD.vmd" is in the folder "MolAICal-xxx\scripts". Copy it in your work directory.
